#!/bin/bash

#=====================================================================================================#

# installdir_colors
# 	This will install the dir_colors file

#=====================================================================================================#

# check for the dir_colors file
if [ -f dir_colors ]; then
	echo "dir_colors file was found in the current working directory."
	echo "It will be installed"
else
	echo "dir_colors file has not been found in the current working directory. Cannot be installed." >&2
	exit 1
fi

# move and rename the dir_colors file
cp dir_colors ~/.dir_colors

# 
echo "The dir_colors file was moved to your HOME directory and changed to a hidden file."
echo "Please use 'ls -la' to view your hidden files in your home directory."

